framework:
    cache:
        # Use file system instead of Redis
        app: cache.adapter.filesystem
        system: cache.adapter.filesystem

        # Namespaced pools
        pools:
            pimcore.cache.pool:
                adapter: cache.adapter.filesystem
                public: true
                tags: true