monolog:
    channels:
        - pimcore
        - pimcore_api
        - session
    
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!event", "!doctrine", "!console"]
        
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        
        pimcore:
            type: stream
            path: "%kernel.logs_dir%/pimcore.log"
            level: error
            channels: [pimcore]
        
        pimcore_api:
            type: stream
            path: "%kernel.logs_dir%/pimcore-api.log"
            level: error
            channels: [pimcore_api]
