pimcore_admin:
    gdpr_data_extractor:
        dataObjects:
            classes:
                product:
                    include: true
                    allowDelete: false
                    includedRelations: []
                category:
                    include: true
                    allowDelete: false
                    includedRelations: []
    branding:
        login_screen_invert_colors: false
        color_login_screen: '#0066FF'
        color_admin_interface: '#0066FF'
        login_screen_custom_image: ''
    admin_languages:
        - en
        - fr
        - ar