security:
    providers:
        pimcore_admin:
            id: Pimcore\Security\User\UserProvider
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        pimcore_admin:
            pattern: ^/admin(/.*)?$
            provider: pimcore_admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login/login
                default_target_path: /admin/
                always_use_default_target_path: false
                username_parameter: username
                password_parameter: password
                csrf_parameter: csrfToken
                csrf_token_id: authenticate
            logout:
                path: /admin/logout
                target: /admin/login
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 2592000
                path: /admin

        website:
            pattern: ^/.*
            provider: pimcore_admin
            security: false

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_PIMCORE_ADMIN }