parameters:
    locale: 'en'
    secret: '%env(APP_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # make classes in src/ available as services, but exclude AppBundle
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/AppBundle/'

    # controllers (allow DI in controller action arguments)
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

